services:
  localstack:
    image: localstack/localstack:0.14.5
    ports:
      - "4566-4583:4566-4583"
    environment:
      - AWS_REGION=us-west-2
      - AWS_ACCESS_KEY_ID=default
      - AWS_SECRET_ACCESS_KEY=default
      - AWS_DEFAULT_REGION=us-west-2
      - EDGE_PORT=4566
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - "localstack:/tmp/localstack" # Mount the volume to the temp path inside the container
      # Mounting the Docker socket /var/run/docker.sock as a volume is required for some services 
      # that use Docker to provide the emulation, such as AWS Lambda
      - "/var/run/docker.sock:/var/run/docker.sock"
      
volumes:
  localstack: # Declare the named volume `localstack`
